// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowseGameFolder():Promise<main.State>;

export function BrowseScreenshotsFolder():Promise<main.State>;

export function ClearGameFolder():Promise<main.State>;

export function ClearScreenshotsFolder():Promise<main.State>;

export function DoUpdate():Promise<main.State>;

export function GetState():Promise<main.State>;

export function OpenPilotPage():Promise<void>;

export function Quit():Promise<void>;

export function SetAutoClean(arg1:boolean):Promise<main.State>;

export function SetAutoStart(arg1:boolean):Promise<main.State>;

export function SetHookId(arg1:string):Promise<main.State>;

export function SetRegion(arg1:string):Promise<main.State>;
