// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseGameFolder() {
  return window['go']['main']['App']['BrowseGameFolder']();
}

export function BrowseScreenshotsFolder() {
  return window['go']['main']['App']['BrowseScreenshotsFolder']();
}

export function ClearGameFolder() {
  return window['go']['main']['App']['ClearGameFolder']();
}

export function ClearScreenshotsFolder() {
  return window['go']['main']['App']['ClearScreenshotsFolder']();
}

export function CreateQuestCharacterAndImport(arg1, arg2) {
  return window['go']['main']['App']['CreateQuestCharacterAndImport'](arg1, arg2);
}

export function DoUpdate() {
  return window['go']['main']['App']['DoUpdate']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ImportQuestProfile(arg1, arg2) {
  return window['go']['main']['App']['ImportQuestProfile'](arg1, arg2);
}

export function OpenPilotPage() {
  return window['go']['main']['App']['OpenPilotPage']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ScanQuestHistory() {
  return window['go']['main']['App']['ScanQuestHistory']();
}

export function SetAutoClean(arg1) {
  return window['go']['main']['App']['SetAutoClean'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetHookId(arg1) {
  return window['go']['main']['App']['SetHookId'](arg1);
}

export function SetRegion(arg1) {
  return window['go']['main']['App']['SetRegion'](arg1);
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}
